package com.sg.fairtech.kafkaapp.product.model;

import com.sg.fairtech.kafkaapp.product.dto.ProductResponse;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "products")
public class ProductModel {

    public ProductModel(Long version, String sku, String name, String description, BigDecimal price) {
        this.version = version;
        this.sku = sku;
        this.name = name;
        this.description = description;
        this.price = price;
    }

    public ProductModel(String name, String description, BigDecimal price, String consumerProductIdentifier) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.consumerProductIdentifier = consumerProductIdentifier;
    }

    public ProductModel(String sku, String name, String description, BigDecimal price, String consumerProductIdentifier) {
        this.version = version;
        this.sku = sku;
        this.name = name;
        this.description = description;
        this.price = price;
        this.consumerProductIdentifier = consumerProductIdentifier;
    }

    public ProductModel(String sku, String name, String description, BigDecimal price) {
        this.sku = sku;
        this.name = name;
        this.description = description;
        this.price = price;
    }

    public ProductModel(String name, String description, BigDecimal price) {
        this.name = name;
        this.description = description;
        this.price = price;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String sku; // SKU: Unique identifier for the product

    @Version
    private Long version;

    private BigDecimal price;

    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;

    private String consumerProductIdentifier; // Only generated by consumer app, for sync identifier
}
